####
# This Dockerfile is used in order to build a container that runs the Spring Boot application in JVM mode
#
# Before building the docker image run:
#
# mvn package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t spring/realworldapiservice-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 spring/realworldapiservice-jvm
#
###
FROM eclipse-temurin:25-jre
WORKDIR /deployments/
COPY target/realworld-api-spring.jar /deployments/app.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/deployments/app.jar" ]
